'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="INTEATRODIG")>  _
Partial Public Class DesvincularDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Definiciones de métodos de extensibilidad"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertIntegrantes(instance As Integrantes)
    End Sub
  Partial Private Sub UpdateIntegrantes(instance As Integrantes)
    End Sub
  Partial Private Sub DeleteIntegrantes(instance As Integrantes)
    End Sub
  Partial Private Sub InsertREGISDIG(instance As REGISDIG)
    End Sub
  Partial Private Sub UpdateREGISDIG(instance As REGISDIG)
    End Sub
  Partial Private Sub DeleteREGISDIG(instance As REGISDIG)
    End Sub
  Partial Private Sub InsertREGISTRO(instance As REGISTRO)
    End Sub
  Partial Private Sub UpdateREGISTRO(instance As REGISTRO)
    End Sub
  Partial Private Sub DeleteREGISTRO(instance As REGISTRO)
    End Sub
  Partial Private Sub InsertSECTORES(instance As SECTORES)
    End Sub
  Partial Private Sub UpdateSECTORES(instance As SECTORES)
    End Sub
  Partial Private Sub DeleteSECTORES(instance As SECTORES)
    End Sub
  Partial Private Sub InsertProvinciasMail(instance As ProvinciasMail)
    End Sub
  Partial Private Sub UpdateProvinciasMail(instance As ProvinciasMail)
    End Sub
  Partial Private Sub DeleteProvinciasMail(instance As ProvinciasMail)
    End Sub
  #End Region
	
	Public Sub New()
        MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("INTEATRODIGConnectionString").ConnectionString, mappingSource)
        OnCreated()
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property Integrantes() As System.Data.Linq.Table(Of Integrantes)
		Get
			Return Me.GetTable(Of Integrantes)
		End Get
	End Property
	
	Public ReadOnly Property REGISDIG() As System.Data.Linq.Table(Of REGISDIG)
		Get
			Return Me.GetTable(Of REGISDIG)
		End Get
	End Property
	
	Public ReadOnly Property REGISTRO() As System.Data.Linq.Table(Of REGISTRO)
		Get
			Return Me.GetTable(Of REGISTRO)
		End Get
	End Property
	
	Public ReadOnly Property SECTORES() As System.Data.Linq.Table(Of SECTORES)
		Get
			Return Me.GetTable(Of SECTORES)
		End Get
	End Property
	
	Public ReadOnly Property ProvinciasMail() As System.Data.Linq.Table(Of ProvinciasMail)
		Get
			Return Me.GetTable(Of ProvinciasMail)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Integrantes")>  _
Partial Public Class Integrantes
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _idIntegrante As Integer
	
	Private _codigoRegistro As System.Nullable(Of Integer)
	
	Private _CUIL As System.Nullable(Of Decimal)
	
	Private _fechaAlta As System.Nullable(Of Date)
	
	Private _fechaBaja As System.Nullable(Of Date)
	
	Private _REGISTRO As EntityRef(Of REGISTRO)
	
	Private _REGISDIG As EntityRef(Of REGISDIG)
	
    #Region "Definiciones de métodos de extensibilidad"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnidIntegranteChanging(value As Integer)
    End Sub
    Partial Private Sub OnidIntegranteChanged()
    End Sub
    Partial Private Sub OncodigoRegistroChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OncodigoRegistroChanged()
    End Sub
    Partial Private Sub OnCUILChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnCUILChanged()
    End Sub
    Partial Private Sub OnfechaAltaChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnfechaAltaChanged()
    End Sub
    Partial Private Sub OnfechaBajaChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnfechaBajaChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._REGISTRO = CType(Nothing, EntityRef(Of REGISTRO))
		Me._REGISDIG = CType(Nothing, EntityRef(Of REGISDIG))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idIntegrante", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property idIntegrante() As Integer
		Get
			Return Me._idIntegrante
		End Get
		Set
			If ((Me._idIntegrante = value)  _
						= false) Then
				Me.OnidIntegranteChanging(value)
				Me.SendPropertyChanging
				Me._idIntegrante = value
				Me.SendPropertyChanged("idIntegrante")
				Me.OnidIntegranteChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_codigoRegistro", DbType:="Int")>  _
	Public Property codigoRegistro() As System.Nullable(Of Integer)
		Get
			Return Me._codigoRegistro
		End Get
		Set
			If (Me._codigoRegistro.Equals(value) = false) Then
				If Me._REGISTRO.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OncodigoRegistroChanging(value)
				Me.SendPropertyChanging
				Me._codigoRegistro = value
				Me.SendPropertyChanged("codigoRegistro")
				Me.OncodigoRegistroChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CUIL", DbType:="Decimal(11,0)")>  _
	Public Property CUIL() As System.Nullable(Of Decimal)
		Get
			Return Me._CUIL
		End Get
		Set
			If (Me._CUIL.Equals(value) = false) Then
				If Me._REGISDIG.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnCUILChanging(value)
				Me.SendPropertyChanging
				Me._CUIL = value
				Me.SendPropertyChanged("CUIL")
				Me.OnCUILChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaAlta", DbType:="DateTime")>  _
	Public Property fechaAlta() As System.Nullable(Of Date)
		Get
			Return Me._fechaAlta
		End Get
		Set
			If (Me._fechaAlta.Equals(value) = false) Then
				Me.OnfechaAltaChanging(value)
				Me.SendPropertyChanging
				Me._fechaAlta = value
				Me.SendPropertyChanged("fechaAlta")
				Me.OnfechaAltaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fechaBaja", DbType:="DateTime")>  _
	Public Property fechaBaja() As System.Nullable(Of Date)
		Get
			Return Me._fechaBaja
		End Get
		Set
			If (Me._fechaBaja.Equals(value) = false) Then
				Me.OnfechaBajaChanging(value)
				Me.SendPropertyChanging
				Me._fechaBaja = value
				Me.SendPropertyChanged("fechaBaja")
				Me.OnfechaBajaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="REGISTRO_Integrantes", Storage:="_REGISTRO", ThisKey:="codigoRegistro", OtherKey:="CODIGO", IsForeignKey:=true)>  _
	Public Property REGISTRO() As REGISTRO
		Get
			Return Me._REGISTRO.Entity
		End Get
		Set
			Dim previousValue As REGISTRO = Me._REGISTRO.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._REGISTRO.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._REGISTRO.Entity = Nothing
					previousValue.Integrantes.Remove(Me)
				End If
				Me._REGISTRO.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.Integrantes.Add(Me)
					Me._codigoRegistro = value.CODIGO
				Else
					Me._codigoRegistro = CType(Nothing, Nullable(Of Integer))
				End If
				Me.SendPropertyChanged("REGISTRO")
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="REGISDIG_Integrantes", Storage:="_REGISDIG", ThisKey:="CUIL", OtherKey:="CUIL", IsForeignKey:=true)>  _
	Public Property REGISDIG() As REGISDIG
		Get
			Return Me._REGISDIG.Entity
		End Get
		Set
			Dim previousValue As REGISDIG = Me._REGISDIG.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._REGISDIG.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._REGISDIG.Entity = Nothing
					previousValue.Integrantes.Remove(Me)
				End If
				Me._REGISDIG.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.Integrantes.Add(Me)
					Me._CUIL = value.CUIL
				Else
					Me._CUIL = CType(Nothing, Nullable(Of Decimal))
				End If
				Me.SendPropertyChanged("REGISDIG")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.REGISDIG")>  _
Partial Public Class REGISDIG
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _CODIGO As Integer
	
	Private _PROVINCIA As Integer
	
	Private _PERSONA As Integer
	
	Private _CUIL As Decimal
	
	Private _FECHNAC As Date
	
	Private _APELLIDO As String
	
	Private _NOMBRE As String
	
	Private _SEXO As Integer
	
	Private _LOCALIDAD As Integer
	
	Private _COPOST As Integer
	
	Private _DOMIPART As String
	
	Private _PREFIPART As Integer
	
	Private _TELEPART As Integer
	
	Private _PREFICELU As Integer
	
	Private _CELUPART As Integer
	
	Private _EMAIL As String
	
	Private _CONTRASENA As String
	
	Private _PREGUNTA As Integer
	
	Private _RESPUESTA As String
	
	Private _DENOMINACION As String
	
	Private _PERSONERIA As String
	
	Private _DOMICILIO As String
	
	Private _FECHALTA As Date
	
	Private _FECHMODI As System.Nullable(Of Date)
	
	Private _NACIONAL As System.Nullable(Of Integer)
	
	Private _RESIDENCIA As System.Nullable(Of Integer)
	
	Private _DOCUMENTO As System.Nullable(Of Integer)
	
	Private _OPEBAJA As String
	
	Private _FECHBAJA As System.Nullable(Of Date)
	
	Private _ACTIVIDAD1 As System.Nullable(Of Integer)
	
	Private _ACTIVIDAD2 As System.Nullable(Of Integer)
	
	Private _ACTIVIDAD3 As System.Nullable(Of Integer)
	
	Private _ACTIVIDAD4 As System.Nullable(Of Integer)
	
	Private _ACTIVIDAD5 As System.Nullable(Of Integer)
	
	Private _ACTIVIDAD6 As System.Nullable(Of Integer)
	
	Private _ACTIVIDAD7 As System.Nullable(Of Integer)
	
	Private _ACTIVIDAD8 As System.Nullable(Of Integer)
	
	Private _ACTIVIDAD9 As System.Nullable(Of Integer)
	
	Private _ACTIVIDAD10 As System.Nullable(Of Integer)
	
	Private _ACTIVIDAD11 As System.Nullable(Of Integer)
	
	Private _ACTIVIDAD12 As System.Nullable(Of Integer)
	
	Private _ACTIVIDAD13 As System.Nullable(Of Integer)
	
	Private _ACTIVIDAD14 As System.Nullable(Of Integer)
	
	Private _confirmado As System.Nullable(Of Integer)
	
	Private _CAMBCLAVE As System.Nullable(Of Integer)
	
	Private _IDEntidadSociedad As System.Nullable(Of Integer)
	
	Private _Integrantes As EntitySet(Of Integrantes)
	
	Private _REGISTRO As EntitySet(Of REGISTRO)
	
	Private _ProvinciasMail As EntityRef(Of ProvinciasMail)
	
    #Region "Definiciones de métodos de extensibilidad"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnCODIGOChanging(value As Integer)
    End Sub
    Partial Private Sub OnCODIGOChanged()
    End Sub
    Partial Private Sub OnPROVINCIAChanging(value As Integer)
    End Sub
    Partial Private Sub OnPROVINCIAChanged()
    End Sub
    Partial Private Sub OnPERSONAChanging(value As Integer)
    End Sub
    Partial Private Sub OnPERSONAChanged()
    End Sub
    Partial Private Sub OnCUILChanging(value As Decimal)
    End Sub
    Partial Private Sub OnCUILChanged()
    End Sub
    Partial Private Sub OnFECHNACChanging(value As Date)
    End Sub
    Partial Private Sub OnFECHNACChanged()
    End Sub
    Partial Private Sub OnAPELLIDOChanging(value As String)
    End Sub
    Partial Private Sub OnAPELLIDOChanged()
    End Sub
    Partial Private Sub OnNOMBREChanging(value As String)
    End Sub
    Partial Private Sub OnNOMBREChanged()
    End Sub
    Partial Private Sub OnSEXOChanging(value As Integer)
    End Sub
    Partial Private Sub OnSEXOChanged()
    End Sub
    Partial Private Sub OnLOCALIDADChanging(value As Integer)
    End Sub
    Partial Private Sub OnLOCALIDADChanged()
    End Sub
    Partial Private Sub OnCOPOSTChanging(value As Integer)
    End Sub
    Partial Private Sub OnCOPOSTChanged()
    End Sub
    Partial Private Sub OnDOMIPARTChanging(value As String)
    End Sub
    Partial Private Sub OnDOMIPARTChanged()
    End Sub
    Partial Private Sub OnPREFIPARTChanging(value As Integer)
    End Sub
    Partial Private Sub OnPREFIPARTChanged()
    End Sub
    Partial Private Sub OnTELEPARTChanging(value As Integer)
    End Sub
    Partial Private Sub OnTELEPARTChanged()
    End Sub
    Partial Private Sub OnPREFICELUChanging(value As Integer)
    End Sub
    Partial Private Sub OnPREFICELUChanged()
    End Sub
    Partial Private Sub OnCELUPARTChanging(value As Integer)
    End Sub
    Partial Private Sub OnCELUPARTChanged()
    End Sub
    Partial Private Sub OnEMAILChanging(value As String)
    End Sub
    Partial Private Sub OnEMAILChanged()
    End Sub
    Partial Private Sub OnCONTRASENAChanging(value As String)
    End Sub
    Partial Private Sub OnCONTRASENAChanged()
    End Sub
    Partial Private Sub OnPREGUNTAChanging(value As Integer)
    End Sub
    Partial Private Sub OnPREGUNTAChanged()
    End Sub
    Partial Private Sub OnRESPUESTAChanging(value As String)
    End Sub
    Partial Private Sub OnRESPUESTAChanged()
    End Sub
    Partial Private Sub OnDENOMINACIONChanging(value As String)
    End Sub
    Partial Private Sub OnDENOMINACIONChanged()
    End Sub
    Partial Private Sub OnPERSONERIAChanging(value As String)
    End Sub
    Partial Private Sub OnPERSONERIAChanged()
    End Sub
    Partial Private Sub OnDOMICILIOChanging(value As String)
    End Sub
    Partial Private Sub OnDOMICILIOChanged()
    End Sub
    Partial Private Sub OnFECHALTAChanging(value As Date)
    End Sub
    Partial Private Sub OnFECHALTAChanged()
    End Sub
    Partial Private Sub OnFECHMODIChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFECHMODIChanged()
    End Sub
    Partial Private Sub OnNACIONALChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnNACIONALChanged()
    End Sub
    Partial Private Sub OnRESIDENCIAChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnRESIDENCIAChanged()
    End Sub
    Partial Private Sub OnDOCUMENTOChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnDOCUMENTOChanged()
    End Sub
    Partial Private Sub OnOPEBAJAChanging(value As String)
    End Sub
    Partial Private Sub OnOPEBAJAChanged()
    End Sub
    Partial Private Sub OnFECHBAJAChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFECHBAJAChanged()
    End Sub
    Partial Private Sub OnACTIVIDAD1Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVIDAD1Changed()
    End Sub
    Partial Private Sub OnACTIVIDAD2Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVIDAD2Changed()
    End Sub
    Partial Private Sub OnACTIVIDAD3Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVIDAD3Changed()
    End Sub
    Partial Private Sub OnACTIVIDAD4Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVIDAD4Changed()
    End Sub
    Partial Private Sub OnACTIVIDAD5Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVIDAD5Changed()
    End Sub
    Partial Private Sub OnACTIVIDAD6Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVIDAD6Changed()
    End Sub
    Partial Private Sub OnACTIVIDAD7Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVIDAD7Changed()
    End Sub
    Partial Private Sub OnACTIVIDAD8Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVIDAD8Changed()
    End Sub
    Partial Private Sub OnACTIVIDAD9Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVIDAD9Changed()
    End Sub
    Partial Private Sub OnACTIVIDAD10Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVIDAD10Changed()
    End Sub
    Partial Private Sub OnACTIVIDAD11Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVIDAD11Changed()
    End Sub
    Partial Private Sub OnACTIVIDAD12Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVIDAD12Changed()
    End Sub
    Partial Private Sub OnACTIVIDAD13Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVIDAD13Changed()
    End Sub
    Partial Private Sub OnACTIVIDAD14Changing(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnACTIVIDAD14Changed()
    End Sub
    Partial Private Sub OnconfirmadoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnconfirmadoChanged()
    End Sub
    Partial Private Sub OnCAMBCLAVEChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnCAMBCLAVEChanged()
    End Sub
    Partial Private Sub OnIDEntidadSociedadChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIDEntidadSociedadChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._Integrantes = New EntitySet(Of Integrantes)(AddressOf Me.attach_Integrantes, AddressOf Me.detach_Integrantes)
		Me._REGISTRO = New EntitySet(Of REGISTRO)(AddressOf Me.attach_REGISTRO, AddressOf Me.detach_REGISTRO)
		Me._ProvinciasMail = CType(Nothing, EntityRef(Of ProvinciasMail))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CODIGO", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property CODIGO() As Integer
		Get
			Return Me._CODIGO
		End Get
		Set
			If ((Me._CODIGO = value)  _
						= false) Then
				Me.OnCODIGOChanging(value)
				Me.SendPropertyChanging
				Me._CODIGO = value
				Me.SendPropertyChanged("CODIGO")
				Me.OnCODIGOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PROVINCIA", DbType:="Int NOT NULL")>  _
	Public Property PROVINCIA() As Integer
		Get
			Return Me._PROVINCIA
		End Get
		Set
			If ((Me._PROVINCIA = value)  _
						= false) Then
				If Me._ProvinciasMail.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnPROVINCIAChanging(value)
				Me.SendPropertyChanging
				Me._PROVINCIA = value
				Me.SendPropertyChanged("PROVINCIA")
				Me.OnPROVINCIAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PERSONA", DbType:="Int NOT NULL")>  _
	Public Property PERSONA() As Integer
		Get
			Return Me._PERSONA
		End Get
		Set
			If ((Me._PERSONA = value)  _
						= false) Then
				Me.OnPERSONAChanging(value)
				Me.SendPropertyChanging
				Me._PERSONA = value
				Me.SendPropertyChanged("PERSONA")
				Me.OnPERSONAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CUIL", DbType:="Decimal(11,0) NOT NULL")>  _
	Public Property CUIL() As Decimal
		Get
			Return Me._CUIL
		End Get
		Set
			If ((Me._CUIL = value)  _
						= false) Then
				Me.OnCUILChanging(value)
				Me.SendPropertyChanging
				Me._CUIL = value
				Me.SendPropertyChanged("CUIL")
				Me.OnCUILChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHNAC", DbType:="DateTime NOT NULL")>  _
	Public Property FECHNAC() As Date
		Get
			Return Me._FECHNAC
		End Get
		Set
			If ((Me._FECHNAC = value)  _
						= false) Then
				Me.OnFECHNACChanging(value)
				Me.SendPropertyChanging
				Me._FECHNAC = value
				Me.SendPropertyChanged("FECHNAC")
				Me.OnFECHNACChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_APELLIDO", DbType:="Char(50) NOT NULL", CanBeNull:=false)>  _
	Public Property APELLIDO() As String
		Get
			Return Me._APELLIDO
		End Get
		Set
			If (String.Equals(Me._APELLIDO, value) = false) Then
				Me.OnAPELLIDOChanging(value)
				Me.SendPropertyChanging
				Me._APELLIDO = value
				Me.SendPropertyChanged("APELLIDO")
				Me.OnAPELLIDOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NOMBRE", DbType:="Char(50) NOT NULL", CanBeNull:=false)>  _
	Public Property NOMBRE() As String
		Get
			Return Me._NOMBRE
		End Get
		Set
			If (String.Equals(Me._NOMBRE, value) = false) Then
				Me.OnNOMBREChanging(value)
				Me.SendPropertyChanging
				Me._NOMBRE = value
				Me.SendPropertyChanged("NOMBRE")
				Me.OnNOMBREChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SEXO", DbType:="Int NOT NULL")>  _
	Public Property SEXO() As Integer
		Get
			Return Me._SEXO
		End Get
		Set
			If ((Me._SEXO = value)  _
						= false) Then
				Me.OnSEXOChanging(value)
				Me.SendPropertyChanging
				Me._SEXO = value
				Me.SendPropertyChanged("SEXO")
				Me.OnSEXOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LOCALIDAD", DbType:="Int NOT NULL")>  _
	Public Property LOCALIDAD() As Integer
		Get
			Return Me._LOCALIDAD
		End Get
		Set
			If ((Me._LOCALIDAD = value)  _
						= false) Then
				Me.OnLOCALIDADChanging(value)
				Me.SendPropertyChanging
				Me._LOCALIDAD = value
				Me.SendPropertyChanged("LOCALIDAD")
				Me.OnLOCALIDADChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COPOST", DbType:="Int NOT NULL")>  _
	Public Property COPOST() As Integer
		Get
			Return Me._COPOST
		End Get
		Set
			If ((Me._COPOST = value)  _
						= false) Then
				Me.OnCOPOSTChanging(value)
				Me.SendPropertyChanging
				Me._COPOST = value
				Me.SendPropertyChanged("COPOST")
				Me.OnCOPOSTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DOMIPART", DbType:="Char(100) NOT NULL", CanBeNull:=false)>  _
	Public Property DOMIPART() As String
		Get
			Return Me._DOMIPART
		End Get
		Set
			If (String.Equals(Me._DOMIPART, value) = false) Then
				Me.OnDOMIPARTChanging(value)
				Me.SendPropertyChanging
				Me._DOMIPART = value
				Me.SendPropertyChanged("DOMIPART")
				Me.OnDOMIPARTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PREFIPART", DbType:="Int NOT NULL")>  _
	Public Property PREFIPART() As Integer
		Get
			Return Me._PREFIPART
		End Get
		Set
			If ((Me._PREFIPART = value)  _
						= false) Then
				Me.OnPREFIPARTChanging(value)
				Me.SendPropertyChanging
				Me._PREFIPART = value
				Me.SendPropertyChanged("PREFIPART")
				Me.OnPREFIPARTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TELEPART", DbType:="Int NOT NULL")>  _
	Public Property TELEPART() As Integer
		Get
			Return Me._TELEPART
		End Get
		Set
			If ((Me._TELEPART = value)  _
						= false) Then
				Me.OnTELEPARTChanging(value)
				Me.SendPropertyChanging
				Me._TELEPART = value
				Me.SendPropertyChanged("TELEPART")
				Me.OnTELEPARTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PREFICELU", DbType:="Int NOT NULL")>  _
	Public Property PREFICELU() As Integer
		Get
			Return Me._PREFICELU
		End Get
		Set
			If ((Me._PREFICELU = value)  _
						= false) Then
				Me.OnPREFICELUChanging(value)
				Me.SendPropertyChanging
				Me._PREFICELU = value
				Me.SendPropertyChanged("PREFICELU")
				Me.OnPREFICELUChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CELUPART", DbType:="Int NOT NULL")>  _
	Public Property CELUPART() As Integer
		Get
			Return Me._CELUPART
		End Get
		Set
			If ((Me._CELUPART = value)  _
						= false) Then
				Me.OnCELUPARTChanging(value)
				Me.SendPropertyChanging
				Me._CELUPART = value
				Me.SendPropertyChanged("CELUPART")
				Me.OnCELUPARTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EMAIL", DbType:="Char(100) NOT NULL", CanBeNull:=false)>  _
	Public Property EMAIL() As String
		Get
			Return Me._EMAIL
		End Get
		Set
			If (String.Equals(Me._EMAIL, value) = false) Then
				Me.OnEMAILChanging(value)
				Me.SendPropertyChanging
				Me._EMAIL = value
				Me.SendPropertyChanged("EMAIL")
				Me.OnEMAILChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CONTRASENA", DbType:="Char(10) NOT NULL", CanBeNull:=false)>  _
	Public Property CONTRASENA() As String
		Get
			Return Me._CONTRASENA
		End Get
		Set
			If (String.Equals(Me._CONTRASENA, value) = false) Then
				Me.OnCONTRASENAChanging(value)
				Me.SendPropertyChanging
				Me._CONTRASENA = value
				Me.SendPropertyChanged("CONTRASENA")
				Me.OnCONTRASENAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PREGUNTA", DbType:="Int NOT NULL")>  _
	Public Property PREGUNTA() As Integer
		Get
			Return Me._PREGUNTA
		End Get
		Set
			If ((Me._PREGUNTA = value)  _
						= false) Then
				Me.OnPREGUNTAChanging(value)
				Me.SendPropertyChanging
				Me._PREGUNTA = value
				Me.SendPropertyChanged("PREGUNTA")
				Me.OnPREGUNTAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RESPUESTA", DbType:="Char(50) NOT NULL", CanBeNull:=false)>  _
	Public Property RESPUESTA() As String
		Get
			Return Me._RESPUESTA
		End Get
		Set
			If (String.Equals(Me._RESPUESTA, value) = false) Then
				Me.OnRESPUESTAChanging(value)
				Me.SendPropertyChanging
				Me._RESPUESTA = value
				Me.SendPropertyChanged("RESPUESTA")
				Me.OnRESPUESTAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DENOMINACION", DbType:="Char(100) NOT NULL", CanBeNull:=false)>  _
	Public Property DENOMINACION() As String
		Get
			Return Me._DENOMINACION
		End Get
		Set
			If (String.Equals(Me._DENOMINACION, value) = false) Then
				Me.OnDENOMINACIONChanging(value)
				Me.SendPropertyChanging
				Me._DENOMINACION = value
				Me.SendPropertyChanged("DENOMINACION")
				Me.OnDENOMINACIONChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PERSONERIA", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property PERSONERIA() As String
		Get
			Return Me._PERSONERIA
		End Get
		Set
			If (String.Equals(Me._PERSONERIA, value) = false) Then
				Me.OnPERSONERIAChanging(value)
				Me.SendPropertyChanging
				Me._PERSONERIA = value
				Me.SendPropertyChanged("PERSONERIA")
				Me.OnPERSONERIAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DOMICILIO", DbType:="Char(100) NOT NULL", CanBeNull:=false)>  _
	Public Property DOMICILIO() As String
		Get
			Return Me._DOMICILIO
		End Get
		Set
			If (String.Equals(Me._DOMICILIO, value) = false) Then
				Me.OnDOMICILIOChanging(value)
				Me.SendPropertyChanging
				Me._DOMICILIO = value
				Me.SendPropertyChanged("DOMICILIO")
				Me.OnDOMICILIOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHALTA", DbType:="DateTime NOT NULL")>  _
	Public Property FECHALTA() As Date
		Get
			Return Me._FECHALTA
		End Get
		Set
			If ((Me._FECHALTA = value)  _
						= false) Then
				Me.OnFECHALTAChanging(value)
				Me.SendPropertyChanging
				Me._FECHALTA = value
				Me.SendPropertyChanged("FECHALTA")
				Me.OnFECHALTAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHMODI", DbType:="DateTime")>  _
	Public Property FECHMODI() As System.Nullable(Of Date)
		Get
			Return Me._FECHMODI
		End Get
		Set
			If (Me._FECHMODI.Equals(value) = false) Then
				Me.OnFECHMODIChanging(value)
				Me.SendPropertyChanging
				Me._FECHMODI = value
				Me.SendPropertyChanged("FECHMODI")
				Me.OnFECHMODIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NACIONAL", DbType:="Int")>  _
	Public Property NACIONAL() As System.Nullable(Of Integer)
		Get
			Return Me._NACIONAL
		End Get
		Set
			If (Me._NACIONAL.Equals(value) = false) Then
				Me.OnNACIONALChanging(value)
				Me.SendPropertyChanging
				Me._NACIONAL = value
				Me.SendPropertyChanged("NACIONAL")
				Me.OnNACIONALChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RESIDENCIA", DbType:="Int")>  _
	Public Property RESIDENCIA() As System.Nullable(Of Integer)
		Get
			Return Me._RESIDENCIA
		End Get
		Set
			If (Me._RESIDENCIA.Equals(value) = false) Then
				Me.OnRESIDENCIAChanging(value)
				Me.SendPropertyChanging
				Me._RESIDENCIA = value
				Me.SendPropertyChanged("RESIDENCIA")
				Me.OnRESIDENCIAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DOCUMENTO", DbType:="Int")>  _
	Public Property DOCUMENTO() As System.Nullable(Of Integer)
		Get
			Return Me._DOCUMENTO
		End Get
		Set
			If (Me._DOCUMENTO.Equals(value) = false) Then
				Me.OnDOCUMENTOChanging(value)
				Me.SendPropertyChanging
				Me._DOCUMENTO = value
				Me.SendPropertyChanged("DOCUMENTO")
				Me.OnDOCUMENTOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OPEBAJA", DbType:="Char(10)")>  _
	Public Property OPEBAJA() As String
		Get
			Return Me._OPEBAJA
		End Get
		Set
			If (String.Equals(Me._OPEBAJA, value) = false) Then
				Me.OnOPEBAJAChanging(value)
				Me.SendPropertyChanging
				Me._OPEBAJA = value
				Me.SendPropertyChanged("OPEBAJA")
				Me.OnOPEBAJAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHBAJA", DbType:="DateTime")>  _
	Public Property FECHBAJA() As System.Nullable(Of Date)
		Get
			Return Me._FECHBAJA
		End Get
		Set
			If (Me._FECHBAJA.Equals(value) = false) Then
				Me.OnFECHBAJAChanging(value)
				Me.SendPropertyChanging
				Me._FECHBAJA = value
				Me.SendPropertyChanged("FECHBAJA")
				Me.OnFECHBAJAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVIDAD1", DbType:="Int")>  _
	Public Property ACTIVIDAD1() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVIDAD1
		End Get
		Set
			If (Me._ACTIVIDAD1.Equals(value) = false) Then
				Me.OnACTIVIDAD1Changing(value)
				Me.SendPropertyChanging
				Me._ACTIVIDAD1 = value
				Me.SendPropertyChanged("ACTIVIDAD1")
				Me.OnACTIVIDAD1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVIDAD2", DbType:="Int")>  _
	Public Property ACTIVIDAD2() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVIDAD2
		End Get
		Set
			If (Me._ACTIVIDAD2.Equals(value) = false) Then
				Me.OnACTIVIDAD2Changing(value)
				Me.SendPropertyChanging
				Me._ACTIVIDAD2 = value
				Me.SendPropertyChanged("ACTIVIDAD2")
				Me.OnACTIVIDAD2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVIDAD3", DbType:="Int")>  _
	Public Property ACTIVIDAD3() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVIDAD3
		End Get
		Set
			If (Me._ACTIVIDAD3.Equals(value) = false) Then
				Me.OnACTIVIDAD3Changing(value)
				Me.SendPropertyChanging
				Me._ACTIVIDAD3 = value
				Me.SendPropertyChanged("ACTIVIDAD3")
				Me.OnACTIVIDAD3Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVIDAD4", DbType:="Int")>  _
	Public Property ACTIVIDAD4() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVIDAD4
		End Get
		Set
			If (Me._ACTIVIDAD4.Equals(value) = false) Then
				Me.OnACTIVIDAD4Changing(value)
				Me.SendPropertyChanging
				Me._ACTIVIDAD4 = value
				Me.SendPropertyChanged("ACTIVIDAD4")
				Me.OnACTIVIDAD4Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVIDAD5", DbType:="Int")>  _
	Public Property ACTIVIDAD5() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVIDAD5
		End Get
		Set
			If (Me._ACTIVIDAD5.Equals(value) = false) Then
				Me.OnACTIVIDAD5Changing(value)
				Me.SendPropertyChanging
				Me._ACTIVIDAD5 = value
				Me.SendPropertyChanged("ACTIVIDAD5")
				Me.OnACTIVIDAD5Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVIDAD6", DbType:="Int")>  _
	Public Property ACTIVIDAD6() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVIDAD6
		End Get
		Set
			If (Me._ACTIVIDAD6.Equals(value) = false) Then
				Me.OnACTIVIDAD6Changing(value)
				Me.SendPropertyChanging
				Me._ACTIVIDAD6 = value
				Me.SendPropertyChanged("ACTIVIDAD6")
				Me.OnACTIVIDAD6Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVIDAD7", DbType:="Int")>  _
	Public Property ACTIVIDAD7() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVIDAD7
		End Get
		Set
			If (Me._ACTIVIDAD7.Equals(value) = false) Then
				Me.OnACTIVIDAD7Changing(value)
				Me.SendPropertyChanging
				Me._ACTIVIDAD7 = value
				Me.SendPropertyChanged("ACTIVIDAD7")
				Me.OnACTIVIDAD7Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVIDAD8", DbType:="Int")>  _
	Public Property ACTIVIDAD8() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVIDAD8
		End Get
		Set
			If (Me._ACTIVIDAD8.Equals(value) = false) Then
				Me.OnACTIVIDAD8Changing(value)
				Me.SendPropertyChanging
				Me._ACTIVIDAD8 = value
				Me.SendPropertyChanged("ACTIVIDAD8")
				Me.OnACTIVIDAD8Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVIDAD9", DbType:="Int")>  _
	Public Property ACTIVIDAD9() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVIDAD9
		End Get
		Set
			If (Me._ACTIVIDAD9.Equals(value) = false) Then
				Me.OnACTIVIDAD9Changing(value)
				Me.SendPropertyChanging
				Me._ACTIVIDAD9 = value
				Me.SendPropertyChanged("ACTIVIDAD9")
				Me.OnACTIVIDAD9Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVIDAD10", DbType:="Int")>  _
	Public Property ACTIVIDAD10() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVIDAD10
		End Get
		Set
			If (Me._ACTIVIDAD10.Equals(value) = false) Then
				Me.OnACTIVIDAD10Changing(value)
				Me.SendPropertyChanging
				Me._ACTIVIDAD10 = value
				Me.SendPropertyChanged("ACTIVIDAD10")
				Me.OnACTIVIDAD10Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVIDAD11", DbType:="Int")>  _
	Public Property ACTIVIDAD11() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVIDAD11
		End Get
		Set
			If (Me._ACTIVIDAD11.Equals(value) = false) Then
				Me.OnACTIVIDAD11Changing(value)
				Me.SendPropertyChanging
				Me._ACTIVIDAD11 = value
				Me.SendPropertyChanged("ACTIVIDAD11")
				Me.OnACTIVIDAD11Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVIDAD12", DbType:="Int")>  _
	Public Property ACTIVIDAD12() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVIDAD12
		End Get
		Set
			If (Me._ACTIVIDAD12.Equals(value) = false) Then
				Me.OnACTIVIDAD12Changing(value)
				Me.SendPropertyChanging
				Me._ACTIVIDAD12 = value
				Me.SendPropertyChanged("ACTIVIDAD12")
				Me.OnACTIVIDAD12Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVIDAD13", DbType:="Int")>  _
	Public Property ACTIVIDAD13() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVIDAD13
		End Get
		Set
			If (Me._ACTIVIDAD13.Equals(value) = false) Then
				Me.OnACTIVIDAD13Changing(value)
				Me.SendPropertyChanging
				Me._ACTIVIDAD13 = value
				Me.SendPropertyChanged("ACTIVIDAD13")
				Me.OnACTIVIDAD13Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVIDAD14", DbType:="Int")>  _
	Public Property ACTIVIDAD14() As System.Nullable(Of Integer)
		Get
			Return Me._ACTIVIDAD14
		End Get
		Set
			If (Me._ACTIVIDAD14.Equals(value) = false) Then
				Me.OnACTIVIDAD14Changing(value)
				Me.SendPropertyChanging
				Me._ACTIVIDAD14 = value
				Me.SendPropertyChanged("ACTIVIDAD14")
				Me.OnACTIVIDAD14Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_confirmado", DbType:="Int")>  _
	Public Property confirmado() As System.Nullable(Of Integer)
		Get
			Return Me._confirmado
		End Get
		Set
			If (Me._confirmado.Equals(value) = false) Then
				Me.OnconfirmadoChanging(value)
				Me.SendPropertyChanging
				Me._confirmado = value
				Me.SendPropertyChanged("confirmado")
				Me.OnconfirmadoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CAMBCLAVE", DbType:="Int")>  _
	Public Property CAMBCLAVE() As System.Nullable(Of Integer)
		Get
			Return Me._CAMBCLAVE
		End Get
		Set
			If (Me._CAMBCLAVE.Equals(value) = false) Then
				Me.OnCAMBCLAVEChanging(value)
				Me.SendPropertyChanging
				Me._CAMBCLAVE = value
				Me.SendPropertyChanged("CAMBCLAVE")
				Me.OnCAMBCLAVEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDEntidadSociedad", DbType:="Int")>  _
	Public Property IDEntidadSociedad() As System.Nullable(Of Integer)
		Get
			Return Me._IDEntidadSociedad
		End Get
		Set
			If (Me._IDEntidadSociedad.Equals(value) = false) Then
				Me.OnIDEntidadSociedadChanging(value)
				Me.SendPropertyChanging
				Me._IDEntidadSociedad = value
				Me.SendPropertyChanged("IDEntidadSociedad")
				Me.OnIDEntidadSociedadChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="REGISDIG_Integrantes", Storage:="_Integrantes", ThisKey:="CUIL", OtherKey:="CUIL")>  _
	Public Property Integrantes() As EntitySet(Of Integrantes)
		Get
			Return Me._Integrantes
		End Get
		Set
			Me._Integrantes.Assign(value)
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="REGISDIG_REGISTRO", Storage:="_REGISTRO", ThisKey:="CODIGO", OtherKey:="RESPONSABLE")>  _
	Public Property REGISTRO() As EntitySet(Of REGISTRO)
		Get
			Return Me._REGISTRO
		End Get
		Set
			Me._REGISTRO.Assign(value)
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="ProvinciasMail_REGISDIG", Storage:="_ProvinciasMail", ThisKey:="PROVINCIA", OtherKey:="idProvincia", IsForeignKey:=true)>  _
	Public Property ProvinciasMail() As ProvinciasMail
		Get
			Return Me._ProvinciasMail.Entity
		End Get
		Set
			Dim previousValue As ProvinciasMail = Me._ProvinciasMail.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._ProvinciasMail.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._ProvinciasMail.Entity = Nothing
					previousValue.REGISDIG.Remove(Me)
				End If
				Me._ProvinciasMail.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.REGISDIG.Add(Me)
					Me._PROVINCIA = value.idProvincia
				Else
					Me._PROVINCIA = CType(Nothing, Integer)
				End If
				Me.SendPropertyChanged("ProvinciasMail")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_Integrantes(ByVal entity As Integrantes)
		Me.SendPropertyChanging
		entity.REGISDIG = Me
	End Sub
	
	Private Sub detach_Integrantes(ByVal entity As Integrantes)
		Me.SendPropertyChanging
		entity.REGISDIG = Nothing
	End Sub
	
	Private Sub attach_REGISTRO(ByVal entity As REGISTRO)
		Me.SendPropertyChanging
		entity.REGISDIG = Me
	End Sub
	
	Private Sub detach_REGISTRO(ByVal entity As REGISTRO)
		Me.SendPropertyChanging
		entity.REGISDIG = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.REGISTRO")>  _
Partial Public Class REGISTRO
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _CODIGO As Integer
	
	Private _REGISTRO As System.Nullable(Of Decimal)
	
	Private _RESPONSABLE As System.Nullable(Of Integer)
	
	Private _SECTOR As System.Nullable(Of Integer)
	
	Private _DENOMINACION As String
	
	Private _LOCALIDAD As System.Nullable(Of Integer)
	
	Private _provincia As System.Nullable(Of Integer)
	
	Private _COPOST As System.Nullable(Of Integer)
	
	Private _DOMICILIO As String
	
	Private _PREFIJO As System.Nullable(Of Integer)
	
	Private _TELEFONO As System.Nullable(Of Integer)
	
	Private _EMAIL As String
	
	Private _PAGINA As String
	
	Private _LOCALIDADES As System.Nullable(Of Integer)
	
	Private _INICIO As System.Nullable(Of Date)
	
	Private _ESPACIO As System.Nullable(Of Integer)
	
	Private _COMESPACIO As String
	
	Private _HABILITACION As System.Nullable(Of Integer)
	
	Private _ESPAESCEN As String
	
	Private _EQUIPAMIENTO As String
	
	Private _CONTRASENA As String
	
	Private _PREGUNTA As System.Nullable(Of Integer)
	
	Private _RESPUESTA As String
	
	Private _ESPAPROP As System.Nullable(Of Integer)
	
	Private _CURRICULUM As String
	
	Private _PROGRASIST As String
	
	Private _INIDOCENTE As System.Nullable(Of Date)
	
	Private _cv As String
	
	Private _AUTOR As String
	
	Private _TIPOPUBLI As System.Nullable(Of Integer)
	
	Private _INICIOACTIV As System.Nullable(Of Date)
	
	Private _FECHCONSTI As System.Nullable(Of Date)
	
	Private _FECHACTA As System.Nullable(Of Date)
	
	Private _VIGENCIA As System.Nullable(Of Integer)
	
	Private _TIPOEVEN As System.Nullable(Of Integer)
	
	Private _DESDE As System.Nullable(Of Date)
	
	Private _HASTA As System.Nullable(Of Date)
	
	Private _FECHALTA As System.Nullable(Of Date)
	
	Private _FECHMODI As System.Nullable(Of Date)
	
	Private _OPEBAJA As String
	
	Private _FECHBAJA As System.Nullable(Of Date)
	
	Private _CONFIRMADO As System.Nullable(Of Integer)
	
	Private _MAILREG As System.Nullable(Of Date)
	
	Private _TEXTOBAJA As String
	
	Private _Integrantes As EntitySet(Of Integrantes)
	
	Private _REGISDIG As EntityRef(Of REGISDIG)
	
	Private _SECTORES As EntityRef(Of SECTORES)
	
    #Region "Definiciones de métodos de extensibilidad"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnCODIGOChanging(value As Integer)
    End Sub
    Partial Private Sub OnCODIGOChanged()
    End Sub
    Partial Private Sub OnREGISTROChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnREGISTROChanged()
    End Sub
    Partial Private Sub OnRESPONSABLEChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnRESPONSABLEChanged()
    End Sub
    Partial Private Sub OnSECTORChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSECTORChanged()
    End Sub
    Partial Private Sub OnDENOMINACIONChanging(value As String)
    End Sub
    Partial Private Sub OnDENOMINACIONChanged()
    End Sub
    Partial Private Sub OnLOCALIDADChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnLOCALIDADChanged()
    End Sub
    Partial Private Sub OnprovinciaChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnprovinciaChanged()
    End Sub
    Partial Private Sub OnCOPOSTChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnCOPOSTChanged()
    End Sub
    Partial Private Sub OnDOMICILIOChanging(value As String)
    End Sub
    Partial Private Sub OnDOMICILIOChanged()
    End Sub
    Partial Private Sub OnPREFIJOChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPREFIJOChanged()
    End Sub
    Partial Private Sub OnTELEFONOChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTELEFONOChanged()
    End Sub
    Partial Private Sub OnEMAILChanging(value As String)
    End Sub
    Partial Private Sub OnEMAILChanged()
    End Sub
    Partial Private Sub OnPAGINAChanging(value As String)
    End Sub
    Partial Private Sub OnPAGINAChanged()
    End Sub
    Partial Private Sub OnLOCALIDADESChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnLOCALIDADESChanged()
    End Sub
    Partial Private Sub OnINICIOChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnINICIOChanged()
    End Sub
    Partial Private Sub OnESPACIOChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnESPACIOChanged()
    End Sub
    Partial Private Sub OnCOMESPACIOChanging(value As String)
    End Sub
    Partial Private Sub OnCOMESPACIOChanged()
    End Sub
    Partial Private Sub OnHABILITACIONChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnHABILITACIONChanged()
    End Sub
    Partial Private Sub OnESPAESCENChanging(value As String)
    End Sub
    Partial Private Sub OnESPAESCENChanged()
    End Sub
    Partial Private Sub OnEQUIPAMIENTOChanging(value As String)
    End Sub
    Partial Private Sub OnEQUIPAMIENTOChanged()
    End Sub
    Partial Private Sub OnCONTRASENAChanging(value As String)
    End Sub
    Partial Private Sub OnCONTRASENAChanged()
    End Sub
    Partial Private Sub OnPREGUNTAChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPREGUNTAChanged()
    End Sub
    Partial Private Sub OnRESPUESTAChanging(value As String)
    End Sub
    Partial Private Sub OnRESPUESTAChanged()
    End Sub
    Partial Private Sub OnESPAPROPChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnESPAPROPChanged()
    End Sub
    Partial Private Sub OnCURRICULUMChanging(value As String)
    End Sub
    Partial Private Sub OnCURRICULUMChanged()
    End Sub
    Partial Private Sub OnPROGRASISTChanging(value As String)
    End Sub
    Partial Private Sub OnPROGRASISTChanged()
    End Sub
    Partial Private Sub OnINIDOCENTEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnINIDOCENTEChanged()
    End Sub
    Partial Private Sub OncvChanging(value As String)
    End Sub
    Partial Private Sub OncvChanged()
    End Sub
    Partial Private Sub OnAUTORChanging(value As String)
    End Sub
    Partial Private Sub OnAUTORChanged()
    End Sub
    Partial Private Sub OnTIPOPUBLIChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTIPOPUBLIChanged()
    End Sub
    Partial Private Sub OnINICIOACTIVChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnINICIOACTIVChanged()
    End Sub
    Partial Private Sub OnFECHCONSTIChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFECHCONSTIChanged()
    End Sub
    Partial Private Sub OnFECHACTAChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFECHACTAChanged()
    End Sub
    Partial Private Sub OnVIGENCIAChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnVIGENCIAChanged()
    End Sub
    Partial Private Sub OnTIPOEVENChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTIPOEVENChanged()
    End Sub
    Partial Private Sub OnDESDEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDESDEChanged()
    End Sub
    Partial Private Sub OnHASTAChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnHASTAChanged()
    End Sub
    Partial Private Sub OnFECHALTAChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFECHALTAChanged()
    End Sub
    Partial Private Sub OnFECHMODIChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFECHMODIChanged()
    End Sub
    Partial Private Sub OnOPEBAJAChanging(value As String)
    End Sub
    Partial Private Sub OnOPEBAJAChanged()
    End Sub
    Partial Private Sub OnFECHBAJAChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFECHBAJAChanged()
    End Sub
    Partial Private Sub OnCONFIRMADOChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnCONFIRMADOChanged()
    End Sub
    Partial Private Sub OnMAILREGChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnMAILREGChanged()
    End Sub
    Partial Private Sub OnTEXTOBAJAChanging(value As String)
    End Sub
    Partial Private Sub OnTEXTOBAJAChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._Integrantes = New EntitySet(Of Integrantes)(AddressOf Me.attach_Integrantes, AddressOf Me.detach_Integrantes)
		Me._REGISDIG = CType(Nothing, EntityRef(Of REGISDIG))
		Me._SECTORES = CType(Nothing, EntityRef(Of SECTORES))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CODIGO", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property CODIGO() As Integer
		Get
			Return Me._CODIGO
		End Get
		Set
			If ((Me._CODIGO = value)  _
						= false) Then
				Me.OnCODIGOChanging(value)
				Me.SendPropertyChanging
				Me._CODIGO = value
				Me.SendPropertyChanged("CODIGO")
				Me.OnCODIGOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REGISTRO", DbType:="Decimal(18,0)")>  _
	Public Property REGISTRO() As System.Nullable(Of Decimal)
		Get
			Return Me._REGISTRO
		End Get
		Set
			If (Me._REGISTRO.Equals(value) = false) Then
				Me.OnREGISTROChanging(value)
				Me.SendPropertyChanging
				Me._REGISTRO = value
				Me.SendPropertyChanged("REGISTRO")
				Me.OnREGISTROChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RESPONSABLE", DbType:="Int")>  _
	Public Property RESPONSABLE() As System.Nullable(Of Integer)
		Get
			Return Me._RESPONSABLE
		End Get
		Set
			If (Me._RESPONSABLE.Equals(value) = false) Then
				If Me._REGISDIG.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnRESPONSABLEChanging(value)
				Me.SendPropertyChanging
				Me._RESPONSABLE = value
				Me.SendPropertyChanged("RESPONSABLE")
				Me.OnRESPONSABLEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SECTOR", DbType:="Int")>  _
	Public Property SECTOR() As System.Nullable(Of Integer)
		Get
			Return Me._SECTOR
		End Get
		Set
			If (Me._SECTOR.Equals(value) = false) Then
				If Me._SECTORES.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnSECTORChanging(value)
				Me.SendPropertyChanging
				Me._SECTOR = value
				Me.SendPropertyChanged("SECTOR")
				Me.OnSECTORChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DENOMINACION", DbType:="Char(200)")>  _
	Public Property DENOMINACION() As String
		Get
			Return Me._DENOMINACION
		End Get
		Set
			If (String.Equals(Me._DENOMINACION, value) = false) Then
				Me.OnDENOMINACIONChanging(value)
				Me.SendPropertyChanging
				Me._DENOMINACION = value
				Me.SendPropertyChanged("DENOMINACION")
				Me.OnDENOMINACIONChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LOCALIDAD", DbType:="Int")>  _
	Public Property LOCALIDAD() As System.Nullable(Of Integer)
		Get
			Return Me._LOCALIDAD
		End Get
		Set
			If (Me._LOCALIDAD.Equals(value) = false) Then
				Me.OnLOCALIDADChanging(value)
				Me.SendPropertyChanging
				Me._LOCALIDAD = value
				Me.SendPropertyChanged("LOCALIDAD")
				Me.OnLOCALIDADChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_provincia", DbType:="Int")>  _
	Public Property provincia() As System.Nullable(Of Integer)
		Get
			Return Me._provincia
		End Get
		Set
			If (Me._provincia.Equals(value) = false) Then
				Me.OnprovinciaChanging(value)
				Me.SendPropertyChanging
				Me._provincia = value
				Me.SendPropertyChanged("provincia")
				Me.OnprovinciaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COPOST", DbType:="Int")>  _
	Public Property COPOST() As System.Nullable(Of Integer)
		Get
			Return Me._COPOST
		End Get
		Set
			If (Me._COPOST.Equals(value) = false) Then
				Me.OnCOPOSTChanging(value)
				Me.SendPropertyChanging
				Me._COPOST = value
				Me.SendPropertyChanged("COPOST")
				Me.OnCOPOSTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DOMICILIO", DbType:="Char(100)")>  _
	Public Property DOMICILIO() As String
		Get
			Return Me._DOMICILIO
		End Get
		Set
			If (String.Equals(Me._DOMICILIO, value) = false) Then
				Me.OnDOMICILIOChanging(value)
				Me.SendPropertyChanging
				Me._DOMICILIO = value
				Me.SendPropertyChanged("DOMICILIO")
				Me.OnDOMICILIOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PREFIJO", DbType:="Int")>  _
	Public Property PREFIJO() As System.Nullable(Of Integer)
		Get
			Return Me._PREFIJO
		End Get
		Set
			If (Me._PREFIJO.Equals(value) = false) Then
				Me.OnPREFIJOChanging(value)
				Me.SendPropertyChanging
				Me._PREFIJO = value
				Me.SendPropertyChanged("PREFIJO")
				Me.OnPREFIJOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TELEFONO", DbType:="Int")>  _
	Public Property TELEFONO() As System.Nullable(Of Integer)
		Get
			Return Me._TELEFONO
		End Get
		Set
			If (Me._TELEFONO.Equals(value) = false) Then
				Me.OnTELEFONOChanging(value)
				Me.SendPropertyChanging
				Me._TELEFONO = value
				Me.SendPropertyChanged("TELEFONO")
				Me.OnTELEFONOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EMAIL", DbType:="Char(100)")>  _
	Public Property EMAIL() As String
		Get
			Return Me._EMAIL
		End Get
		Set
			If (String.Equals(Me._EMAIL, value) = false) Then
				Me.OnEMAILChanging(value)
				Me.SendPropertyChanging
				Me._EMAIL = value
				Me.SendPropertyChanged("EMAIL")
				Me.OnEMAILChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PAGINA", DbType:="Char(100)")>  _
	Public Property PAGINA() As String
		Get
			Return Me._PAGINA
		End Get
		Set
			If (String.Equals(Me._PAGINA, value) = false) Then
				Me.OnPAGINAChanging(value)
				Me.SendPropertyChanging
				Me._PAGINA = value
				Me.SendPropertyChanged("PAGINA")
				Me.OnPAGINAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LOCALIDADES", DbType:="Int")>  _
	Public Property LOCALIDADES() As System.Nullable(Of Integer)
		Get
			Return Me._LOCALIDADES
		End Get
		Set
			If (Me._LOCALIDADES.Equals(value) = false) Then
				Me.OnLOCALIDADESChanging(value)
				Me.SendPropertyChanging
				Me._LOCALIDADES = value
				Me.SendPropertyChanged("LOCALIDADES")
				Me.OnLOCALIDADESChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_INICIO", DbType:="DateTime")>  _
	Public Property INICIO() As System.Nullable(Of Date)
		Get
			Return Me._INICIO
		End Get
		Set
			If (Me._INICIO.Equals(value) = false) Then
				Me.OnINICIOChanging(value)
				Me.SendPropertyChanging
				Me._INICIO = value
				Me.SendPropertyChanged("INICIO")
				Me.OnINICIOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ESPACIO", DbType:="Int")>  _
	Public Property ESPACIO() As System.Nullable(Of Integer)
		Get
			Return Me._ESPACIO
		End Get
		Set
			If (Me._ESPACIO.Equals(value) = false) Then
				Me.OnESPACIOChanging(value)
				Me.SendPropertyChanging
				Me._ESPACIO = value
				Me.SendPropertyChanged("ESPACIO")
				Me.OnESPACIOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COMESPACIO", DbType:="Char(200)")>  _
	Public Property COMESPACIO() As String
		Get
			Return Me._COMESPACIO
		End Get
		Set
			If (String.Equals(Me._COMESPACIO, value) = false) Then
				Me.OnCOMESPACIOChanging(value)
				Me.SendPropertyChanging
				Me._COMESPACIO = value
				Me.SendPropertyChanged("COMESPACIO")
				Me.OnCOMESPACIOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HABILITACION", DbType:="Int")>  _
	Public Property HABILITACION() As System.Nullable(Of Integer)
		Get
			Return Me._HABILITACION
		End Get
		Set
			If (Me._HABILITACION.Equals(value) = false) Then
				Me.OnHABILITACIONChanging(value)
				Me.SendPropertyChanging
				Me._HABILITACION = value
				Me.SendPropertyChanged("HABILITACION")
				Me.OnHABILITACIONChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ESPAESCEN", DbType:="Char(200)")>  _
	Public Property ESPAESCEN() As String
		Get
			Return Me._ESPAESCEN
		End Get
		Set
			If (String.Equals(Me._ESPAESCEN, value) = false) Then
				Me.OnESPAESCENChanging(value)
				Me.SendPropertyChanging
				Me._ESPAESCEN = value
				Me.SendPropertyChanged("ESPAESCEN")
				Me.OnESPAESCENChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EQUIPAMIENTO", DbType:="Char(200)")>  _
	Public Property EQUIPAMIENTO() As String
		Get
			Return Me._EQUIPAMIENTO
		End Get
		Set
			If (String.Equals(Me._EQUIPAMIENTO, value) = false) Then
				Me.OnEQUIPAMIENTOChanging(value)
				Me.SendPropertyChanging
				Me._EQUIPAMIENTO = value
				Me.SendPropertyChanged("EQUIPAMIENTO")
				Me.OnEQUIPAMIENTOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CONTRASENA", DbType:="Char(10)")>  _
	Public Property CONTRASENA() As String
		Get
			Return Me._CONTRASENA
		End Get
		Set
			If (String.Equals(Me._CONTRASENA, value) = false) Then
				Me.OnCONTRASENAChanging(value)
				Me.SendPropertyChanging
				Me._CONTRASENA = value
				Me.SendPropertyChanged("CONTRASENA")
				Me.OnCONTRASENAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PREGUNTA", DbType:="Int")>  _
	Public Property PREGUNTA() As System.Nullable(Of Integer)
		Get
			Return Me._PREGUNTA
		End Get
		Set
			If (Me._PREGUNTA.Equals(value) = false) Then
				Me.OnPREGUNTAChanging(value)
				Me.SendPropertyChanging
				Me._PREGUNTA = value
				Me.SendPropertyChanged("PREGUNTA")
				Me.OnPREGUNTAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RESPUESTA", DbType:="Char(100)")>  _
	Public Property RESPUESTA() As String
		Get
			Return Me._RESPUESTA
		End Get
		Set
			If (String.Equals(Me._RESPUESTA, value) = false) Then
				Me.OnRESPUESTAChanging(value)
				Me.SendPropertyChanging
				Me._RESPUESTA = value
				Me.SendPropertyChanged("RESPUESTA")
				Me.OnRESPUESTAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ESPAPROP", DbType:="Int")>  _
	Public Property ESPAPROP() As System.Nullable(Of Integer)
		Get
			Return Me._ESPAPROP
		End Get
		Set
			If (Me._ESPAPROP.Equals(value) = false) Then
				Me.OnESPAPROPChanging(value)
				Me.SendPropertyChanging
				Me._ESPAPROP = value
				Me.SendPropertyChanged("ESPAPROP")
				Me.OnESPAPROPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CURRICULUM", DbType:="Text", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property CURRICULUM() As String
		Get
			Return Me._CURRICULUM
		End Get
		Set
			If (String.Equals(Me._CURRICULUM, value) = false) Then
				Me.OnCURRICULUMChanging(value)
				Me.SendPropertyChanging
				Me._CURRICULUM = value
				Me.SendPropertyChanged("CURRICULUM")
				Me.OnCURRICULUMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PROGRASIST", DbType:="Text", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property PROGRASIST() As String
		Get
			Return Me._PROGRASIST
		End Get
		Set
			If (String.Equals(Me._PROGRASIST, value) = false) Then
				Me.OnPROGRASISTChanging(value)
				Me.SendPropertyChanging
				Me._PROGRASIST = value
				Me.SendPropertyChanged("PROGRASIST")
				Me.OnPROGRASISTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_INIDOCENTE", DbType:="DateTime")>  _
	Public Property INIDOCENTE() As System.Nullable(Of Date)
		Get
			Return Me._INIDOCENTE
		End Get
		Set
			If (Me._INIDOCENTE.Equals(value) = false) Then
				Me.OnINIDOCENTEChanging(value)
				Me.SendPropertyChanging
				Me._INIDOCENTE = value
				Me.SendPropertyChanged("INIDOCENTE")
				Me.OnINIDOCENTEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cv", DbType:="VarChar(3000)")>  _
	Public Property cv() As String
		Get
			Return Me._cv
		End Get
		Set
			If (String.Equals(Me._cv, value) = false) Then
				Me.OncvChanging(value)
				Me.SendPropertyChanging
				Me._cv = value
				Me.SendPropertyChanged("cv")
				Me.OncvChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AUTOR", DbType:="Char(100)")>  _
	Public Property AUTOR() As String
		Get
			Return Me._AUTOR
		End Get
		Set
			If (String.Equals(Me._AUTOR, value) = false) Then
				Me.OnAUTORChanging(value)
				Me.SendPropertyChanging
				Me._AUTOR = value
				Me.SendPropertyChanged("AUTOR")
				Me.OnAUTORChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOPUBLI", DbType:="Int")>  _
	Public Property TIPOPUBLI() As System.Nullable(Of Integer)
		Get
			Return Me._TIPOPUBLI
		End Get
		Set
			If (Me._TIPOPUBLI.Equals(value) = false) Then
				Me.OnTIPOPUBLIChanging(value)
				Me.SendPropertyChanging
				Me._TIPOPUBLI = value
				Me.SendPropertyChanged("TIPOPUBLI")
				Me.OnTIPOPUBLIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_INICIOACTIV", DbType:="DateTime")>  _
	Public Property INICIOACTIV() As System.Nullable(Of Date)
		Get
			Return Me._INICIOACTIV
		End Get
		Set
			If (Me._INICIOACTIV.Equals(value) = false) Then
				Me.OnINICIOACTIVChanging(value)
				Me.SendPropertyChanging
				Me._INICIOACTIV = value
				Me.SendPropertyChanged("INICIOACTIV")
				Me.OnINICIOACTIVChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHCONSTI", DbType:="DateTime")>  _
	Public Property FECHCONSTI() As System.Nullable(Of Date)
		Get
			Return Me._FECHCONSTI
		End Get
		Set
			If (Me._FECHCONSTI.Equals(value) = false) Then
				Me.OnFECHCONSTIChanging(value)
				Me.SendPropertyChanging
				Me._FECHCONSTI = value
				Me.SendPropertyChanged("FECHCONSTI")
				Me.OnFECHCONSTIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHACTA", DbType:="DateTime")>  _
	Public Property FECHACTA() As System.Nullable(Of Date)
		Get
			Return Me._FECHACTA
		End Get
		Set
			If (Me._FECHACTA.Equals(value) = false) Then
				Me.OnFECHACTAChanging(value)
				Me.SendPropertyChanging
				Me._FECHACTA = value
				Me.SendPropertyChanged("FECHACTA")
				Me.OnFECHACTAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VIGENCIA", DbType:="Int")>  _
	Public Property VIGENCIA() As System.Nullable(Of Integer)
		Get
			Return Me._VIGENCIA
		End Get
		Set
			If (Me._VIGENCIA.Equals(value) = false) Then
				Me.OnVIGENCIAChanging(value)
				Me.SendPropertyChanging
				Me._VIGENCIA = value
				Me.SendPropertyChanged("VIGENCIA")
				Me.OnVIGENCIAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIPOEVEN", DbType:="Int")>  _
	Public Property TIPOEVEN() As System.Nullable(Of Integer)
		Get
			Return Me._TIPOEVEN
		End Get
		Set
			If (Me._TIPOEVEN.Equals(value) = false) Then
				Me.OnTIPOEVENChanging(value)
				Me.SendPropertyChanging
				Me._TIPOEVEN = value
				Me.SendPropertyChanged("TIPOEVEN")
				Me.OnTIPOEVENChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DESDE", DbType:="DateTime")>  _
	Public Property DESDE() As System.Nullable(Of Date)
		Get
			Return Me._DESDE
		End Get
		Set
			If (Me._DESDE.Equals(value) = false) Then
				Me.OnDESDEChanging(value)
				Me.SendPropertyChanging
				Me._DESDE = value
				Me.SendPropertyChanged("DESDE")
				Me.OnDESDEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HASTA", DbType:="DateTime")>  _
	Public Property HASTA() As System.Nullable(Of Date)
		Get
			Return Me._HASTA
		End Get
		Set
			If (Me._HASTA.Equals(value) = false) Then
				Me.OnHASTAChanging(value)
				Me.SendPropertyChanging
				Me._HASTA = value
				Me.SendPropertyChanged("HASTA")
				Me.OnHASTAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHALTA", DbType:="DateTime")>  _
	Public Property FECHALTA() As System.Nullable(Of Date)
		Get
			Return Me._FECHALTA
		End Get
		Set
			If (Me._FECHALTA.Equals(value) = false) Then
				Me.OnFECHALTAChanging(value)
				Me.SendPropertyChanging
				Me._FECHALTA = value
				Me.SendPropertyChanged("FECHALTA")
				Me.OnFECHALTAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHMODI", DbType:="DateTime")>  _
	Public Property FECHMODI() As System.Nullable(Of Date)
		Get
			Return Me._FECHMODI
		End Get
		Set
			If (Me._FECHMODI.Equals(value) = false) Then
				Me.OnFECHMODIChanging(value)
				Me.SendPropertyChanging
				Me._FECHMODI = value
				Me.SendPropertyChanged("FECHMODI")
				Me.OnFECHMODIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OPEBAJA", DbType:="Char(10)")>  _
	Public Property OPEBAJA() As String
		Get
			Return Me._OPEBAJA
		End Get
		Set
			If (String.Equals(Me._OPEBAJA, value) = false) Then
				Me.OnOPEBAJAChanging(value)
				Me.SendPropertyChanging
				Me._OPEBAJA = value
				Me.SendPropertyChanged("OPEBAJA")
				Me.OnOPEBAJAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FECHBAJA", DbType:="DateTime")>  _
	Public Property FECHBAJA() As System.Nullable(Of Date)
		Get
			Return Me._FECHBAJA
		End Get
		Set
			If (Me._FECHBAJA.Equals(value) = false) Then
				Me.OnFECHBAJAChanging(value)
				Me.SendPropertyChanging
				Me._FECHBAJA = value
				Me.SendPropertyChanged("FECHBAJA")
				Me.OnFECHBAJAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CONFIRMADO", DbType:="Int")>  _
	Public Property CONFIRMADO() As System.Nullable(Of Integer)
		Get
			Return Me._CONFIRMADO
		End Get
		Set
			If (Me._CONFIRMADO.Equals(value) = false) Then
				Me.OnCONFIRMADOChanging(value)
				Me.SendPropertyChanging
				Me._CONFIRMADO = value
				Me.SendPropertyChanged("CONFIRMADO")
				Me.OnCONFIRMADOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MAILREG", DbType:="DateTime")>  _
	Public Property MAILREG() As System.Nullable(Of Date)
		Get
			Return Me._MAILREG
		End Get
		Set
			If (Me._MAILREG.Equals(value) = false) Then
				Me.OnMAILREGChanging(value)
				Me.SendPropertyChanging
				Me._MAILREG = value
				Me.SendPropertyChanged("MAILREG")
				Me.OnMAILREGChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TEXTOBAJA", DbType:="Char(200)")>  _
	Public Property TEXTOBAJA() As String
		Get
			Return Me._TEXTOBAJA
		End Get
		Set
			If (String.Equals(Me._TEXTOBAJA, value) = false) Then
				Me.OnTEXTOBAJAChanging(value)
				Me.SendPropertyChanging
				Me._TEXTOBAJA = value
				Me.SendPropertyChanged("TEXTOBAJA")
				Me.OnTEXTOBAJAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="REGISTRO_Integrantes", Storage:="_Integrantes", ThisKey:="CODIGO", OtherKey:="codigoRegistro")>  _
	Public Property Integrantes() As EntitySet(Of Integrantes)
		Get
			Return Me._Integrantes
		End Get
		Set
			Me._Integrantes.Assign(value)
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="REGISDIG_REGISTRO", Storage:="_REGISDIG", ThisKey:="RESPONSABLE", OtherKey:="CODIGO", IsForeignKey:=true)>  _
	Public Property REGISDIG() As REGISDIG
		Get
			Return Me._REGISDIG.Entity
		End Get
		Set
			Dim previousValue As REGISDIG = Me._REGISDIG.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._REGISDIG.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._REGISDIG.Entity = Nothing
					previousValue.REGISTRO.Remove(Me)
				End If
				Me._REGISDIG.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.REGISTRO.Add(Me)
					Me._RESPONSABLE = value.CODIGO
				Else
					Me._RESPONSABLE = CType(Nothing, Nullable(Of Integer))
				End If
				Me.SendPropertyChanged("REGISDIG")
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SECTORES_REGISTRO", Storage:="_SECTORES", ThisKey:="SECTOR", OtherKey:="CODIGO", IsForeignKey:=true)>  _
	Public Property SECTORES() As SECTORES
		Get
			Return Me._SECTORES.Entity
		End Get
		Set
			Dim previousValue As SECTORES = Me._SECTORES.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._SECTORES.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._SECTORES.Entity = Nothing
					previousValue.REGISTRO.Remove(Me)
				End If
				Me._SECTORES.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.REGISTRO.Add(Me)
					Me._SECTOR = value.CODIGO
				Else
					Me._SECTOR = CType(Nothing, Nullable(Of Integer))
				End If
				Me.SendPropertyChanged("SECTORES")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_Integrantes(ByVal entity As Integrantes)
		Me.SendPropertyChanging
		entity.REGISTRO = Me
	End Sub
	
	Private Sub detach_Integrantes(ByVal entity As Integrantes)
		Me.SendPropertyChanging
		entity.REGISTRO = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SECTORES")>  _
Partial Public Class SECTORES
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _CODIGO As Integer
	
	Private _DESCRIP As String
	
	Private _CODIVIEJO As System.Nullable(Of Integer)
	
	Private _ENTIDAD As System.Nullable(Of Integer)
	
	Private _SOCIEDAD As System.Nullable(Of Integer)
	
	Private _REGISTRO As EntitySet(Of REGISTRO)
	
    #Region "Definiciones de métodos de extensibilidad"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnCODIGOChanging(value As Integer)
    End Sub
    Partial Private Sub OnCODIGOChanged()
    End Sub
    Partial Private Sub OnDESCRIPChanging(value As String)
    End Sub
    Partial Private Sub OnDESCRIPChanged()
    End Sub
    Partial Private Sub OnCODIVIEJOChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnCODIVIEJOChanged()
    End Sub
    Partial Private Sub OnENTIDADChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnENTIDADChanged()
    End Sub
    Partial Private Sub OnSOCIEDADChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSOCIEDADChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._REGISTRO = New EntitySet(Of REGISTRO)(AddressOf Me.attach_REGISTRO, AddressOf Me.detach_REGISTRO)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CODIGO", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property CODIGO() As Integer
		Get
			Return Me._CODIGO
		End Get
		Set
			If ((Me._CODIGO = value)  _
						= false) Then
				Me.OnCODIGOChanging(value)
				Me.SendPropertyChanging
				Me._CODIGO = value
				Me.SendPropertyChanged("CODIGO")
				Me.OnCODIGOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DESCRIP", DbType:="Char(50)")>  _
	Public Property DESCRIP() As String
		Get
			Return Me._DESCRIP
		End Get
		Set
			If (String.Equals(Me._DESCRIP, value) = false) Then
				Me.OnDESCRIPChanging(value)
				Me.SendPropertyChanging
				Me._DESCRIP = value
				Me.SendPropertyChanged("DESCRIP")
				Me.OnDESCRIPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CODIVIEJO", DbType:="Int")>  _
	Public Property CODIVIEJO() As System.Nullable(Of Integer)
		Get
			Return Me._CODIVIEJO
		End Get
		Set
			If (Me._CODIVIEJO.Equals(value) = false) Then
				Me.OnCODIVIEJOChanging(value)
				Me.SendPropertyChanging
				Me._CODIVIEJO = value
				Me.SendPropertyChanged("CODIVIEJO")
				Me.OnCODIVIEJOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ENTIDAD", DbType:="Int")>  _
	Public Property ENTIDAD() As System.Nullable(Of Integer)
		Get
			Return Me._ENTIDAD
		End Get
		Set
			If (Me._ENTIDAD.Equals(value) = false) Then
				Me.OnENTIDADChanging(value)
				Me.SendPropertyChanging
				Me._ENTIDAD = value
				Me.SendPropertyChanged("ENTIDAD")
				Me.OnENTIDADChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SOCIEDAD", DbType:="Int")>  _
	Public Property SOCIEDAD() As System.Nullable(Of Integer)
		Get
			Return Me._SOCIEDAD
		End Get
		Set
			If (Me._SOCIEDAD.Equals(value) = false) Then
				Me.OnSOCIEDADChanging(value)
				Me.SendPropertyChanging
				Me._SOCIEDAD = value
				Me.SendPropertyChanged("SOCIEDAD")
				Me.OnSOCIEDADChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="SECTORES_REGISTRO", Storage:="_REGISTRO", ThisKey:="CODIGO", OtherKey:="SECTOR")>  _
	Public Property REGISTRO() As EntitySet(Of REGISTRO)
		Get
			Return Me._REGISTRO
		End Get
		Set
			Me._REGISTRO.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_REGISTRO(ByVal entity As REGISTRO)
		Me.SendPropertyChanging
		entity.SECTORES = Me
	End Sub
	
	Private Sub detach_REGISTRO(ByVal entity As REGISTRO)
		Me.SendPropertyChanging
		entity.SECTORES = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ProvinciasMail")>  _
Partial Public Class ProvinciasMail
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _idProvincia As Integer
	
	Private _mail As String
	
	Private _REGISDIG As EntitySet(Of REGISDIG)
	
    #Region "Definiciones de métodos de extensibilidad"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnidProvinciaChanging(value As Integer)
    End Sub
    Partial Private Sub OnidProvinciaChanged()
    End Sub
    Partial Private Sub OnmailChanging(value As String)
    End Sub
    Partial Private Sub OnmailChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._REGISDIG = New EntitySet(Of REGISDIG)(AddressOf Me.attach_REGISDIG, AddressOf Me.detach_REGISDIG)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idProvincia", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property idProvincia() As Integer
		Get
			Return Me._idProvincia
		End Get
		Set
			If ((Me._idProvincia = value)  _
						= false) Then
				Me.OnidProvinciaChanging(value)
				Me.SendPropertyChanging
				Me._idProvincia = value
				Me.SendPropertyChanged("idProvincia")
				Me.OnidProvinciaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_mail", DbType:="VarChar(40)")>  _
	Public Property mail() As String
		Get
			Return Me._mail
		End Get
		Set
			If (String.Equals(Me._mail, value) = false) Then
				Me.OnmailChanging(value)
				Me.SendPropertyChanging
				Me._mail = value
				Me.SendPropertyChanged("mail")
				Me.OnmailChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="ProvinciasMail_REGISDIG", Storage:="_REGISDIG", ThisKey:="idProvincia", OtherKey:="PROVINCIA")>  _
	Public Property REGISDIG() As EntitySet(Of REGISDIG)
		Get
			Return Me._REGISDIG
		End Get
		Set
			Me._REGISDIG.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_REGISDIG(ByVal entity As REGISDIG)
		Me.SendPropertyChanging
		entity.ProvinciasMail = Me
	End Sub
	
	Private Sub detach_REGISDIG(ByVal entity As REGISDIG)
		Me.SendPropertyChanging
		entity.ProvinciasMail = Nothing
	End Sub
End Class
